# Generated by Django 3.1.3 on 2020-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_like_article',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='model_user_article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
