# Generated by Django 3.1.3 on 2020-12-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201209_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_like_article',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='model_user_article',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='model_user_article',
            name='header',
            field=models.CharField(max_length=200),
        ),
    ]
